### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by introt** [julien-h/python-template#1]
Greetings!

I found my way here through one of your blog posts which had the same issue as this repo: you haven't specified a license for the code. This means people can't legally use your code in their projects.

For more information on code licensing, see eg. https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/

**Comment by julien-h** [comment]
Hello, thanks for the issue.
I added MIT License to this template.

**Comment by julien-h** [comment]
Regarding my blog posts, there is a copyright at the bottom of the page. Let's not discuss that here. You are welcome to leave a comment on the blog if needed.
